### ISSUE TITLE
下载到最后报 invalid json ，相册没有全部下载下来

### ISSUE THREAD

**Issue by ChinaArJun** [qinjintian/qq-zone#1]

**Comment by qinjintian** [comment]
请问你是选择下载好友相册还是下载自己的呢？可以描述一下吗？如果出现在获取QQ空间相册的时候出现  invalid json 大部分情况是因为QQ空间无响应或者服务器繁忙等情况，可以重新执行下载一遍，本地已经下载过的相片和视频程序会自动跳过的，很快就可以执行完成

**Comment by ChinaArJun** [comment]
OK,用Windows环境下载没有问题了，Linux下容易出现一些异常

**Comment by qinjintian** [comment]
> OK,用Windows环境下载没有问题了，Linux下容易出现一些异常

好的！谢谢反馈，我是windows环境测试的，linux没试过，我这就测试一下
