### ISSUE TITLE
问题qq空间怎么登陆

### ISSUE THREAD

**Issue by mj5219054** [qinjintian/qq-zone#2]
你这怎么登陆啊

**Comment by qinjintian** [comment]
windows系统下可以直接下载qq-zone. exe文件到本地电脑，然后双击运行按照终端提示操作根目录下会生成一个登录二维码，通过手机qq扫码登录即可自动下载。-------- 原始邮件 --------发件人： 朝露 ***@***.***>日期： 2021年5月24日周一 01:07收件人： qinjintian/qq-zone ***@***.***>抄送： Subscribed ***@***.***>主    题： [qinjintian/qq-zone] 问题qq空间怎么登陆 (#2)

你这怎么登陆啊

**Comment by mj5219054** [comment]
感谢作者回复。以操作成功
