### ISSUE TITLE
日志提示相册名字出现空格下载失败

### ISSUE THREAD

**Issue by wanxings** [qinjintian/qq-zone#3]
如果相册名字结尾出现空格（我也不知道怎么来的，打印报错信息的时候出现的），会下载失败
![image](https://user-images.githubusercontent.com/37164409/121316496-fc6a2400-c93b-11eb-9bd9-6e30cc92335c.png)

在app\controllers\QzoneController.go 497行
resp, err := myhttp.Download(source, target, header, 5, 600, false)
前对target去除空格就好了

**Comment by qinjintian** [comment]
感谢您反馈了问题，由于工作原因，该bug我会周末抽时间修复，请关注。

**Comment by qinjintian** [comment]
您反馈的问题已修复。
