### ISSUE TITLE
在下载空间相册的时候 只下载了前30个相册

### ISSUE THREAD

**Issue by kmakise** [qinjintian/qq-zone#6]
在下载空间相册的时候 只下载了前30相册，win10 Powershell ，手动输入后面的相册名字也无法下载

**Comment by qinjintian** [comment]
某些相册下载不成功基本是因为相册名命名不规范造成的，请检查相册名是否符合Windows下命名~~~

**Comment by qinjintian** [comment]
> 在下载空间相册的时候 只下载了前30相册，win10 Powershell ，手动输入后面的相册名字也无法下载

某些相册下载不成功基本是因为相册名命名不规范造成的，请检查相册名是否符合Windows下命名~~~

**Comment by kmakise** [comment]
我打印获取列表的时候也发现只有30个 包括用其他的脚本也存在这个问题

**Comment by kmakise** [comment]
网页打开的话如果不拉动的话 默认加载的就是三十个相册 会不会这个有关系

**Comment by qinjintian** [comment]
> 网页打开的话如果不拉动的话 默认加载的就是三十个相册 会不会这个有关系
确实存在这问题，这个我再找时间修复，目前第30个相册之后的先手动输入吧

**Comment by qinjintian** [comment]
> 网页打开的话如果不拉动的话 默认加载的就是三十个相册 会不会这个有关系

已修复
