### ISSUE TITLE
问题求助，下载时出现加密照片以及失败

### ISSUE THREAD

**Issue by CriticalService** [qinjintian/qq-zone#7]
使用此程序下载好友相册时，最后提示失败了12个，而且下载到的照片里大约有九百张是96×96 gif格式的**加密照片**（准确地说是20221127以前上传的所有照片），今天再试了一次也是这样……用正常途径访问时所有照片都可以看到

![捕获2](https://user-images.githubusercontent.com/88526082/176800443-2970e3e2-0964-4850-8413-d59c98cff322.PNG)

![捕获](https://user-images.githubusercontent.com/88526082/176800484-185e9f3c-4bb6-413d-bccb-1f3753a35130.PNG)

**Comment by qinjintian** [comment]
> 使用此程序下载好友相册时，最后提示失败了12个，而且下载到的照片里大约有九百张是96×96 gif格式的**加密照片**（准确地说是20221127以前上传的所有照片），今天再试了一次也是这样……用正常途径访问时所有照片都可以看到
> 
> ![捕获2](https://user-images.githubusercontent.com/88526082/176800443-2970e3e2-0964-4850-8413-d59c98cff322.PNG)
> 
> ![捕获](https://user-images.githubusercontent.com/88526082/176800484-185e9f3c-4bb6-413d-bccb-1f3753a35130.PNG)

只能下载好友公开状态的相册，暂不支持下载加密状态的相册

**Comment by CriticalService** [comment]
> 只能下载好友公开状态的相册，暂不支持下载加密状态的相册

只下载了一个相册，下载到的**有些是*加密照片*，有些是正常的。**虽然这个相册权限是部分好友可见，但我使用正常途径访问此相册时所有照片都能显示。

**Comment by qinjintian** [comment]
> 

你应该是下载了好友的【说说和日志相册】，空间说说和日志附带的图片一般都默认存在该相册内，有些图可以正常下载下来，有些却是显示“加密相片”是因为有些说说不是公开状态，所以说说附带的图片也会变为了私密状态，不可正常下载。你应该是属于这类情况

**Comment by CriticalService** [comment]
> 你应该是下载了好友的【说说和日志相册】，空间说说和日志附带的图片一般都默认存在该相册内，有些图可以正常下载下来，有些却是显示“加密相片”是因为有些说说不是公开状态，所以说说附带的图片也会变为了私密状态，不可正常下载。你应该是属于这类情况

（抱歉过了这么久才回复……）

不是说说和日志相册。这个好友的空间权限是三天可见，很多下载成功的照片都超过这个时间了。而且加密照片都是今年11月27日以前上传的照片。
