### ISSUE TITLE
黄钻用户下载视频的时候，下载的不是上传的原画质 

### ISSUE THREAD

**Issue by cnkant** [qinjintian/qq-zone#8]
黄钻用户下载视频的时候，下载的不是上传的原画质，楼主可以修复下吗？经测试，在视频详情页的下载按钮，点击下载后出现的视频是原画
![image](https://user-images.githubusercontent.com/78336221/221467105-8318d458-361c-4fff-abc7-d5721bfec05a.png)

**Comment by qinjintian** [comment]
> 黄钻用户下载视频的时候，下载的不是上传的原画质，楼主可以修复下吗？经测试，在视频详情页的下载按钮，点击下载后出现的视频是原画 ![image](https://user-images.githubusercontent.com/78336221/221467105-8318d458-361c-4fff-abc7-d5721bfec05a.png)

黄钻用户我没有验证过，因为我不是账号不是慌钻所以看不到返回的URL格式和免费版的有啥区别

**Comment by cnkant** [comment]
可以把下载视频的链接换成新的链接嘛老大

**Comment by cnkant** [comment]
可以给你找个黄钻账号提供测试

**Comment by qinjintian** [comment]
> 可以把下载视频的链接换成新的链接嘛老大

最近忙着工作，可能一时间还没顾得上改

**Comment by cnkant** [comment]
近期有时间修复吗大佬，改个下载链接应该用不了很久~

**Comment by qinjintian** [comment]
> 近期有时间修复吗大佬，改个下载链接应该用不了很久~

我没有黄钻号，方便的话你可以提供一下黄钻测试号。联系：514092640

**Comment by cnkant** [comment]
好的
